FROM postgres:9.6.2-alpine
#COPY init-fastnet-db.sh /docker-entrypoint-initdb.d/
#COPY ./docker/postgres/init-fastnet-db.sh /docker-entrypoint-initdb.d/
#COPY init-fastnet-db.sh /docker-entrypoint-initdb.d/

# ENV POSTGRES_USER postgres

#COPY init-db.sh /docker-entrypoint-initdb.d/
