FROM jboss/keycloak:3.3.0.Final

# Env vars are expected for DB Details, defaults are only for local envs
#ENV BD jdbc:postgresql://localhost:5442/keyclockdb
#ENV DB_URL jdbc:postgresql://postgresql-rockall:5432/fastnet
#ENV DB_USER postgres
#ENV DB_PASSWORD postgres