version: '3'
services:
  keyclock-postgres:
    build:
      dockerfile: docker/keyclock-postgres-data-base/Dockerfile
      context: .
    image: ey/keyclock-postgres-data-base
    container_name: ey-keyclock-postgres-data-base
    volumes:
      - ./docker/keyclock-postgres-data-base/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5442:5432"
    networks:
      - ey-network

  keyclock:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT_5432_TCP_ADDR=ey-keyclock-postgres-data-base
      - POSTGRES_DATABASE=keyclockdb
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    build:
      dockerfile: docker/keyclock/Dockerfile
      context: .
    image: ey/keyclock
    container_name: ey-keyclock
    ports:
      - "8080:8080"
      - "9990:9990"
      - "443:443"
    depends_on:
      - keyclock-postgres
    networks:
      - ey-network


  wildfly:
    build:
#      dockerfile: docker/wildfly/Dockerfile
#      context: .
      dockerfile: Dockerfile
      context: ./docker/wildfly/
    image: ey/wildfly
    container_name: ey-wildfly
#    volumes:
#      - ./docker/wildfly:opt/jboss/wildfly/customization
    ports:
      - "8180:8080"
      - "10090:9990"
      - "543:9990"
    depends_on:
      - keyclock-postgres
      - keyclock
    networks:
      - ey-network


#volumes:
#  docker/keyclock-postgres-data-base/docker-entrypoint-initdb.d:

networks:
  ey-network:
    driver: bridge